### ISSUE TITLE
why was hamcrest dependency removed in build.gradle

### ISSUE THREAD

**Issue by poorguy-tech** [jxnu-liguobin/cs-summary-reflection#34]
Since you have used `junit4.12` for unit test, why was hamcrest removed in build.gradle? 
It causes `java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing` Error.

**Comment by poorguy-tech** [comment]
It seems that I got the wrong message on the Internet, https://github.com/junit-team/junit4/wiki/Use-with-Gradle.

**Comment by jxnu-liguobin** [comment]
The test was not added by me, so I didn't pay attention to it. 
At present, I only focus on the compilation results of contributors. 
You should resolve it
