### ISSUE TITLE
Permission denied when pushing.

### ISSUE THREAD

**Issue by sweeneycai** [jxnu-liguobin/cs-summary-reflection#40]
Pushing to https://github.com/jxnu-liguobin/cs-summary-reflection.git
remote: Permission to jxnu-liguobin/cs-summary-reflection.git denied to sweeneycai.
fatal: unable to access 'https://github.com/jxnu-liguobin/cs-summary-reflection.git/': The requested URL returned error: 403

**Comment by jxnu-liguobin** [comment]
Oh, I hava forgot

**Comment by jxnu-liguobin** [comment]
I've invited you

**Comment by sweeneycai** [comment]
Accept and problem solved, thx.

**Comment by jxnu-liguobin** [comment]
> Accept and problem solved, thx.

You should not use `git revert` to rollback my commit, so that my commit will be lost.
You should use `git commit`, then `git rebase `or `git pull`, and then push. I've fixed the problem.
Before each push, you should execute `git pull` to update the local master branch.

**Comment by sweeneycai** [comment]
> > Accept and problem solved, thx.
> 
> You should not use `git revert` to rollback my commit, so that my commit will be lost.
> You should use `git commit`, then `git rebase `or `git pull`, and then push. I've fixed the problem.
> Before each push, you should execute `git pull` to update the local master branch.

Sorry for a careless `revert` operation, I will execute `git pull` the next time and thx for your interpretation.
